/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InternshipApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'role' : IDL.Text,
  'dateApplied' : IDL.Text,
  'company' : IDL.Text,
});
export const MockInterviewQuestion = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'subcategory' : IDL.Text,
  'category' : IDL.Text,
});
export const PracticeQuestion = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const ReminderSettings = IDL.Record({
  'dailyTime' : IDL.Text,
  'monthlyEnabled' : IDL.Bool,
  'weeklyDay' : IDL.Text,
  'dailyEnabled' : IDL.Bool,
  'monthlyDay' : IDL.Nat,
  'weeklyEnabled' : IDL.Bool,
});
export const ResumeData = IDL.Record({
  'projects' : IDL.Text,
  'education' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'summary' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
});
export const RoadmapProgress = IDL.Record({
  'completionPercent' : IDL.Nat,
  'monthIndex' : IDL.Nat,
  'completedTopics' : IDL.Vec(IDL.Bool),
});
export const Skill = IDL.Record({
  'skillName' : IDL.Text,
  'lastPracticedDate' : IDL.Text,
  'level' : IDL.Nat,
  'progressPercent' : IDL.Nat,
});
export const SolvedQuestion = IDL.Record({
  'solvedDate' : IDL.Text,
  'notes' : IDL.Text,
  'questionId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'totalSolvedQuestions' : IDL.Nat,
  'lastActiveDate' : IDL.Text,
  'currentStreak' : IDL.Nat,
});
export const MockInterviewAnswer = IDL.Record({
  'answer' : IDL.Text,
  'questionId' : IDL.Text,
  'rating' : IDL.Nat,
  'answeredDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'addInternshipApplication' : IDL.Func([InternshipApplication], [], []),
  'deleteInternshipApplication' : IDL.Func([IDL.Text], [], []),
  'getAllMockInterviewQuestions' : IDL.Func(
      [],
      [IDL.Vec(MockInterviewQuestion)],
      ['query'],
    ),
  'getAllPracticeQuestions' : IDL.Func(
      [],
      [IDL.Vec(PracticeQuestion)],
      ['query'],
    ),
  'getInternshipApplications' : IDL.Func(
      [],
      [IDL.Vec(InternshipApplication)],
      ['query'],
    ),
  'getInternshipApplicationsSortedByCompany' : IDL.Func(
      [],
      [IDL.Vec(InternshipApplication)],
      ['query'],
    ),
  'getInternshipApplicationsSortedByDate' : IDL.Func(
      [],
      [IDL.Vec(InternshipApplication)],
      ['query'],
    ),
  'getPracticeQuestionsByDifficulty' : IDL.Func(
      [],
      [IDL.Vec(PracticeQuestion)],
      ['query'],
    ),
  'getReminderSettings' : IDL.Func([], [IDL.Opt(ReminderSettings)], ['query']),
  'getResumeData' : IDL.Func([], [IDL.Opt(ResumeData)], ['query']),
  'getRoadmapProgress' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RoadmapProgress)],
      ['query'],
    ),
  'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'getSolvedQuestions' : IDL.Func([], [IDL.Vec(SolvedQuestion)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'markQuestionSolved' : IDL.Func([SolvedQuestion], [], []),
  'saveMockInterviewAnswer' : IDL.Func([MockInterviewAnswer], [], []),
  'updateInternshipApplication' : IDL.Func([InternshipApplication], [], []),
  'updateReminderSettings' : IDL.Func([ReminderSettings], [], []),
  'updateResumeData' : IDL.Func([ResumeData], [], []),
  'updateRoadmapProgress' : IDL.Func([RoadmapProgress], [], []),
  'updateSkills' : IDL.Func([IDL.Vec(Skill)], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InternshipApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'role' : IDL.Text,
    'dateApplied' : IDL.Text,
    'company' : IDL.Text,
  });
  const MockInterviewQuestion = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'subcategory' : IDL.Text,
    'category' : IDL.Text,
  });
  const PracticeQuestion = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const ReminderSettings = IDL.Record({
    'dailyTime' : IDL.Text,
    'monthlyEnabled' : IDL.Bool,
    'weeklyDay' : IDL.Text,
    'dailyEnabled' : IDL.Bool,
    'monthlyDay' : IDL.Nat,
    'weeklyEnabled' : IDL.Bool,
  });
  const ResumeData = IDL.Record({
    'projects' : IDL.Text,
    'education' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'summary' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
  });
  const RoadmapProgress = IDL.Record({
    'completionPercent' : IDL.Nat,
    'monthIndex' : IDL.Nat,
    'completedTopics' : IDL.Vec(IDL.Bool),
  });
  const Skill = IDL.Record({
    'skillName' : IDL.Text,
    'lastPracticedDate' : IDL.Text,
    'level' : IDL.Nat,
    'progressPercent' : IDL.Nat,
  });
  const SolvedQuestion = IDL.Record({
    'solvedDate' : IDL.Text,
    'notes' : IDL.Text,
    'questionId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'totalSolvedQuestions' : IDL.Nat,
    'lastActiveDate' : IDL.Text,
    'currentStreak' : IDL.Nat,
  });
  const MockInterviewAnswer = IDL.Record({
    'answer' : IDL.Text,
    'questionId' : IDL.Text,
    'rating' : IDL.Nat,
    'answeredDate' : IDL.Text,
  });
  
  return IDL.Service({
    'addInternshipApplication' : IDL.Func([InternshipApplication], [], []),
    'deleteInternshipApplication' : IDL.Func([IDL.Text], [], []),
    'getAllMockInterviewQuestions' : IDL.Func(
        [],
        [IDL.Vec(MockInterviewQuestion)],
        ['query'],
      ),
    'getAllPracticeQuestions' : IDL.Func(
        [],
        [IDL.Vec(PracticeQuestion)],
        ['query'],
      ),
    'getInternshipApplications' : IDL.Func(
        [],
        [IDL.Vec(InternshipApplication)],
        ['query'],
      ),
    'getInternshipApplicationsSortedByCompany' : IDL.Func(
        [],
        [IDL.Vec(InternshipApplication)],
        ['query'],
      ),
    'getInternshipApplicationsSortedByDate' : IDL.Func(
        [],
        [IDL.Vec(InternshipApplication)],
        ['query'],
      ),
    'getPracticeQuestionsByDifficulty' : IDL.Func(
        [],
        [IDL.Vec(PracticeQuestion)],
        ['query'],
      ),
    'getReminderSettings' : IDL.Func(
        [],
        [IDL.Opt(ReminderSettings)],
        ['query'],
      ),
    'getResumeData' : IDL.Func([], [IDL.Opt(ResumeData)], ['query']),
    'getRoadmapProgress' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RoadmapProgress)],
        ['query'],
      ),
    'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'getSolvedQuestions' : IDL.Func([], [IDL.Vec(SolvedQuestion)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'markQuestionSolved' : IDL.Func([SolvedQuestion], [], []),
    'saveMockInterviewAnswer' : IDL.Func([MockInterviewAnswer], [], []),
    'updateInternshipApplication' : IDL.Func([InternshipApplication], [], []),
    'updateReminderSettings' : IDL.Func([ReminderSettings], [], []),
    'updateResumeData' : IDL.Func([ResumeData], [], []),
    'updateRoadmapProgress' : IDL.Func([RoadmapProgress], [], []),
    'updateSkills' : IDL.Func([IDL.Vec(Skill)], [], []),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };