/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InternshipApplication {
  'id' : string,
  'status' : string,
  'role' : string,
  'dateApplied' : string,
  'company' : string,
}
export interface MockInterviewAnswer {
  'answer' : string,
  'questionId' : string,
  'rating' : bigint,
  'answeredDate' : string,
}
export interface MockInterviewQuestion {
  'id' : string,
  'question' : string,
  'subcategory' : string,
  'category' : string,
}
export interface PracticeQuestion {
  'id' : string,
  'title' : string,
  'difficulty' : string,
  'description' : string,
  'category' : string,
}
export interface ReminderSettings {
  'dailyTime' : string,
  'monthlyEnabled' : boolean,
  'weeklyDay' : string,
  'dailyEnabled' : boolean,
  'monthlyDay' : bigint,
  'weeklyEnabled' : boolean,
}
export interface ResumeData {
  'projects' : string,
  'education' : string,
  'fullName' : string,
  'email' : string,
  'summary' : string,
  'phone' : string,
  'skills' : string,
}
export interface RoadmapProgress {
  'completionPercent' : bigint,
  'monthIndex' : bigint,
  'completedTopics' : Array<boolean>,
}
export interface Skill {
  'skillName' : string,
  'lastPracticedDate' : string,
  'level' : bigint,
  'progressPercent' : bigint,
}
export interface SolvedQuestion {
  'solvedDate' : string,
  'notes' : string,
  'questionId' : string,
}
export interface UserProfile {
  'name' : string,
  'totalSolvedQuestions' : bigint,
  'lastActiveDate' : string,
  'currentStreak' : bigint,
}
export interface _SERVICE {
  'addInternshipApplication' : ActorMethod<[InternshipApplication], undefined>,
  'deleteInternshipApplication' : ActorMethod<[string], undefined>,
  'getAllMockInterviewQuestions' : ActorMethod<
    [],
    Array<MockInterviewQuestion>
  >,
  'getAllPracticeQuestions' : ActorMethod<[], Array<PracticeQuestion>>,
  'getInternshipApplications' : ActorMethod<[], Array<InternshipApplication>>,
  'getInternshipApplicationsSortedByCompany' : ActorMethod<
    [],
    Array<InternshipApplication>
  >,
  'getInternshipApplicationsSortedByDate' : ActorMethod<
    [],
    Array<InternshipApplication>
  >,
  'getPracticeQuestionsByDifficulty' : ActorMethod<[], Array<PracticeQuestion>>,
  'getReminderSettings' : ActorMethod<[], [] | [ReminderSettings]>,
  'getResumeData' : ActorMethod<[], [] | [ResumeData]>,
  'getRoadmapProgress' : ActorMethod<[bigint], [] | [RoadmapProgress]>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
  'getSolvedQuestions' : ActorMethod<[], Array<SolvedQuestion>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'markQuestionSolved' : ActorMethod<[SolvedQuestion], undefined>,
  'saveMockInterviewAnswer' : ActorMethod<[MockInterviewAnswer], undefined>,
  'updateInternshipApplication' : ActorMethod<
    [InternshipApplication],
    undefined
  >,
  'updateReminderSettings' : ActorMethod<[ReminderSettings], undefined>,
  'updateResumeData' : ActorMethod<[ResumeData], undefined>,
  'updateRoadmapProgress' : ActorMethod<[RoadmapProgress], undefined>,
  'updateSkills' : ActorMethod<[Array<Skill>], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];