/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MockInterviewQuestion {
    id: string;
    question: string;
    subcategory: string;
    category: string;
}
export interface MockInterviewAnswer {
    answer: string;
    questionId: string;
    rating: bigint;
    answeredDate: string;
}
export interface SolvedQuestion {
    solvedDate: string;
    notes: string;
    questionId: string;
}
export interface ReminderSettings {
    dailyTime: string;
    monthlyEnabled: boolean;
    weeklyDay: string;
    dailyEnabled: boolean;
    monthlyDay: bigint;
    weeklyEnabled: boolean;
}
export interface Skill {
    skillName: string;
    lastPracticedDate: string;
    level: bigint;
    progressPercent: bigint;
}
export interface InternshipApplication {
    id: string;
    status: string;
    role: string;
    dateApplied: string;
    company: string;
}
export interface ResumeData {
    projects: string;
    education: string;
    fullName: string;
    email: string;
    summary: string;
    phone: string;
    skills: string;
}
export interface PracticeQuestion {
    id: string;
    title: string;
    difficulty: string;
    description: string;
    category: string;
}
export interface UserProfile {
    name: string;
    totalSolvedQuestions: bigint;
    lastActiveDate: string;
    currentStreak: bigint;
}
export interface RoadmapProgress {
    completionPercent: bigint;
    monthIndex: bigint;
    completedTopics: Array<boolean>;
}
export interface backendInterface {
    addInternshipApplication(app: InternshipApplication): Promise<void>;
    deleteInternshipApplication(id: string): Promise<void>;
    getAllMockInterviewQuestions(): Promise<Array<MockInterviewQuestion>>;
    getAllPracticeQuestions(): Promise<Array<PracticeQuestion>>;
    getInternshipApplications(): Promise<Array<InternshipApplication>>;
    getInternshipApplicationsSortedByCompany(): Promise<Array<InternshipApplication>>;
    getInternshipApplicationsSortedByDate(): Promise<Array<InternshipApplication>>;
    getPracticeQuestionsByDifficulty(): Promise<Array<PracticeQuestion>>;
    getReminderSettings(): Promise<ReminderSettings | null>;
    getResumeData(): Promise<ResumeData | null>;
    getRoadmapProgress(month: bigint): Promise<RoadmapProgress | null>;
    getSkills(): Promise<Array<Skill>>;
    getSolvedQuestions(): Promise<Array<SolvedQuestion>>;
    getUserProfile(): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    markQuestionSolved(solved: SolvedQuestion): Promise<void>;
    saveMockInterviewAnswer(answer: MockInterviewAnswer): Promise<void>;
    updateInternshipApplication(app: InternshipApplication): Promise<void>;
    updateReminderSettings(settings: ReminderSettings): Promise<void>;
    updateResumeData(data: ResumeData): Promise<void>;
    updateRoadmapProgress(progress: RoadmapProgress): Promise<void>;
    updateSkills(newSkills: Array<Skill>): Promise<void>;
    updateUserProfile(profile: UserProfile): Promise<void>;
}
import type { ReminderSettings as _ReminderSettings, ResumeData as _ResumeData, RoadmapProgress as _RoadmapProgress, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addInternshipApplication(arg0: InternshipApplication): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInternshipApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInternshipApplication(arg0);
            return result;
        }
    }
    async deleteInternshipApplication(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInternshipApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInternshipApplication(arg0);
            return result;
        }
    }
    async getAllMockInterviewQuestions(): Promise<Array<MockInterviewQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMockInterviewQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMockInterviewQuestions();
            return result;
        }
    }
    async getAllPracticeQuestions(): Promise<Array<PracticeQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPracticeQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPracticeQuestions();
            return result;
        }
    }
    async getInternshipApplications(): Promise<Array<InternshipApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInternshipApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInternshipApplications();
            return result;
        }
    }
    async getInternshipApplicationsSortedByCompany(): Promise<Array<InternshipApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInternshipApplicationsSortedByCompany();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInternshipApplicationsSortedByCompany();
            return result;
        }
    }
    async getInternshipApplicationsSortedByDate(): Promise<Array<InternshipApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInternshipApplicationsSortedByDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInternshipApplicationsSortedByDate();
            return result;
        }
    }
    async getPracticeQuestionsByDifficulty(): Promise<Array<PracticeQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPracticeQuestionsByDifficulty();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPracticeQuestionsByDifficulty();
            return result;
        }
    }
    async getReminderSettings(): Promise<ReminderSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminderSettings();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminderSettings();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResumeData(): Promise<ResumeData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumeData();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumeData();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoadmapProgress(arg0: bigint): Promise<RoadmapProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoadmapProgress(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoadmapProgress(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkills(): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkills();
            return result;
        }
    }
    async getSolvedQuestions(): Promise<Array<SolvedQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSolvedQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSolvedQuestions();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async markQuestionSolved(arg0: SolvedQuestion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markQuestionSolved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markQuestionSolved(arg0);
            return result;
        }
    }
    async saveMockInterviewAnswer(arg0: MockInterviewAnswer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMockInterviewAnswer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMockInterviewAnswer(arg0);
            return result;
        }
    }
    async updateInternshipApplication(arg0: InternshipApplication): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInternshipApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInternshipApplication(arg0);
            return result;
        }
    }
    async updateReminderSettings(arg0: ReminderSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminderSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminderSettings(arg0);
            return result;
        }
    }
    async updateResumeData(arg0: ResumeData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResumeData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResumeData(arg0);
            return result;
        }
    }
    async updateRoadmapProgress(arg0: RoadmapProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoadmapProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoadmapProgress(arg0);
            return result;
        }
    }
    async updateSkills(arg0: Array<Skill>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkills(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkills(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReminderSettings]): ReminderSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResumeData]): ResumeData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoadmapProgress]): RoadmapProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
